; (Optional) This section provides global settings shared across all presets.
; If the same key is defined in a specific preset, it will override the value in this global section.
[*]
n-gpu-layers = auto

; If the key corresponds to an existing model in hf cache, the model  will be served from cache
; If the key does NOT correspond to an existing model,
; specifying HF repo causes download model when model load is requested
[ggml-org/gemma-4-E2B-it-GGUF:Q4_0]
hf-repo = ggml-org/gemma-4-E2B-it-GGUF:Q4_0
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 4
jinja = true
alias = gemma-4-e2b

[ggml-org/gemma-4-E4B-it-GGUF:Q4_0]
hf-repo = ggml-org/gemma-4-E4B-it-GGUF:Q4_0
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 4
jinja = true
alias = gemma-4-e4b

[ggml-org/gemma-4-12B-it-GGUF:Q4_0]
hf-repo = ggml-org/gemma-4-12B-it-GGUF:Q4_0
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 4
jinja = true
alias = gemma-4-12b

[ggml-org/gemma-4-26B-A4B-it-GGUF:Q4_0]
hf-repo = ggml-org/gemma-4-26B-A4B-it-GGUF:Q4_0
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 2
cpu-moe = true
jinja = true
alias = gemma-4-26b-a4b

[ggml-org/Qwen3.6-35B-A3B-GGUF:Q4_K_M]
hf-repo = ggml-org/Qwen3.6-35B-A3B-GGUF:Q4_K_M
; spec-type = draft-mtp,draft-eagle3
; spec-draft-n-max = 2
cpu-moe = true
jinja = true
alias = qwen3.6-35b-a3b

[ggml-org/NVIDIA-Nemotron-3-Nano-Omni:Q4_K_M]
hf-repo = ggml-org/NVIDIA-Nemotron-3-Nano-Omni:Q4_K_M
cpu-moe = true
jinja = true
alias = nemotron-3-nano-omni-30b-a3b

[ggml-org/Qwen3.6-27B-GGUF::Q4_K_M]
hf-repo = ggml-org/Qwen3.6-27B-GGUF::Q4_K_M
; spec-type = draft-mtp,draft-eagle3
; spec-draft-n-max = 2
jinja = true
alias = qwen3.6-27b

[ggml-org/gemma-4-31B-it-GGUF:Q4_0]
hf-repo = ggml-org/gemma-4-31B-it-GGUF:Q4_0
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 2
jinja = true
alias = gemma-4-31b

; [stepfun-ai/Step-3.7-Flash-GGUF:Q4_K_S]
; hf-repo = stepfun-ai/Step-3.7-Flash-GGUF:Q4_K_S
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 2
; jinja = true
; alias = step-3.7-flash
