; (Optional) This section provides global settings shared across all presets.
; If the same key is defined in a specific preset, it will override the value in this global section.
[*]
n-gpu-layers = auto

; If the key corresponds to an existing model in hf cache, the model  will be served from cache
; If the key does NOT correspond to an existing model,
; specifying HF repo causes download model when model load is requested
[unsloth/gemma-4-E2B-it-GGUF:UD-Q4_K_XL]
hf-repo = unsloth/gemma-4-E2B-it-GGUF:UD-Q4_K_XL
; spec-type = draft-mtp
; spec-draft-n-max = 3
cpu-moe = true
jinja = true

[unsloth/gemma-4-E4B-it-GGUF:UD-Q4_K_XL]
hf-repo = unsloth/gemma-4-E4B-it-GGUF:UD-Q4_K_XL
; spec-type = draft-mtp
; spec-draft-n-max = 3
cpu-moe = true
jinja = true

[unsloth/gemma-4-12b-it-GGUF:UD-Q4_K_XL]
hf-repo = unsloth/gemma-4-12b-it-GGUF:UD-Q4_K_XL
; spec-type = draft-mtp
; spec-draft-n-max = 2
jinja = true

[unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL]
hf-repo = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL
; spec-type = draft-mtp
; spec-draft-n-max = 2
cpu-moe = true
jinja = true

[unsloth/Qwen3.6-35B-A3B-MTP-GGUF:Q4_K_XL]
hf-repo = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:Q4_K_XL
; spec-type = draft-mtp
; spec-draft-n-max = 2
cpu-moe = true
jinja = true

; [unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q4_K_XL]
; hf-repo = unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q4_K_XL
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 2
; jinja = true

; [unsloth/gemma-4-31B-it-GGUF:UD-Q4_K_XL]
; hf-repo = unsloth/gemma-4-31B-it-GGUF:UD-Q4_K_XL
; spec-type = draft-mtp,ngram-mod,ngram-map-k4v
; spec-draft-n-max = 2
; jinja = true


